version: '3.4'
 
networks:
  backend:
 
services:
  authenticationdb:
    container_name: authentication_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password123@
    networks:
      - backend
    ports:
      - 8001:1433
  authenticationapi:
    container_name: api-authentication
    image: unpark.azurecr.io/authenticationapi:dev
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=authentication
      - DB_SA_PASSWORD=password123@
 
 
  apiocelotgateway:
    container_name: api_gateway
    image: unpark.azurecr.io/apiocelotgateway:dev
    build:
      context: .
      dockerfile: ApiOcelotGateway/Dockerfile
    ports:
      - 8000:80
    networks:
      - backend

  paymentservice:
    container_name: api_payment
    image: unpark.azurecr.io/paymentservice:dev
    build:
      context: .
      dockerfile: Microservices/PaymentService/Dockerfile
    networks:
      - backend

  userapi:
    container_name: api-user
    image: unpark.azurecr.io/userapi:dev
    build:
      context: .
      dockerfile: Microservices/UserAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=userdb
      - DB_SA_PASSWORD=password123@

  parkapi:
    container_name: api-park
    image: unpark.azurecr.io/parkapi:dev
    build:
      context: .
      dockerfile: Microservices/ParkAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=ParkDb
      - DB_SA_PASSWORD=password123@

  rentalserviceapi:
    container_name: api-rental
    image: unpark.azurecr.io/rentalserviceapi:dev
    build:
      context: .
      dockerfile: Microservices/RentalServiceAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=rentaldb
      - DB_SA_PASSWORD=password123@