version: '3.4'

services:
  apiocelotgateway:
    container_name: api-ocelotgateway
    image: ${DOCKER_REGISTRY-}apiocelotgateway
    build:
      context: .
      dockerfile: ApiOcelotGateway/Dockerfile
    ports:
      - 8001:80
    networks:
      - backend
networks:
  backend:
    driver : bridge      