version: '3.4'

networks:
  backend:

services:
  authenticationdb:
    container_name: authentication_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password123@
    networks:
      - backend
    ports:
      - 8001:1433
      
  authenticationapi:
    container_name: api-authentication
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: AuthenticationAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=authentication
      - DB_SA_PASSWORD=password123@



  apiocelotgateway:
    container_name: api_gateway
    image: ${DOCKER_REGISTRY-}apiocelotgateway
    build:
      context: .
      dockerfile: ApiOcelotGateway/Dockerfile
    ports:
      - 8000:80
    networks:
      - backend


  paymentservice:
    container_name: api_payment
    image: ${DOCKER_REGISTRY-}paymentservice
    build:
      context: .
      dockerfile: Microservices/PaymentService/Dockerfile
    networks:
      - backend


  userapi:
    container_name: api-user
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Microservices/UserAPI/Dockerfile
    networks:
      - backend
    environment:
      - DB_HOST=authenticationdb
      - DB_NAME=userdb
      - DB_SA_PASSWORD=password123@

